### ISSUE TITLE
No cwnd column exists in flowgrind 0.7.5 output

### ISSUE THREAD

**Issue by richi235** [flowgrind/flowgrind#211]
**Version:**   flowgrind 0.7.5 on Debian testing (installed via official Debian repo)

No cwnd column is visible neither in terminal output nor in log-file.
Example:
```
# ID  begin    end       through transac min IAT avg IAT max IAT uack sack lost retr tret fack reor bkof ca state   pmtu
#       [s]    [s]      [Mbit/s]   [#/s]    [ms]    [ms]    [ms]  [#]  [#]  [#]  [#]  [#]  [#]  [#]  [#]             [B]
S  0  0.100  0.150  10296.105295    0.00     inf     inf     inf    1    0    0    0    0    0    3    0     open  65536
D  0  0.150  0.200      0.000000    0.00   0.003   0.005   0.046    0    0    0    0    0    0    3    0     open  65536

```

Other tools like `ss -i` or `ip tcp_metrics` show the cwnd value.
I remember getting the cwnd value in an older (self compiled) version of flowgrind.

I couldn't find an option in the man page to select or enable the cwnd column or output format.

For me, this issue is quite grave, because the variance of cwnd values is the main data point of my experiments on TCP packet reordering. The easy way of obtaining them was the reason I chose flowgrind in the first place.

**Comment by arnd** [comment]
Hi richi,

There should be! Apparently it's broken in this version. Probably because some bug in the freebsd/linux detection. I'll look further. Thanks for the report.

**Comment by csamsel** [comment]
works fine in gentoo

**Comment by arnd** [comment]
Hi Richi,

The problem was already fixed in next by alex in commit 4391c57c75cc5cb80f1bdb92f5f4b786de573e42
So you could give the flowgrind version in next a try.
I'll try to make a new release until the end of next week and get it uploaded. However it will take two more weeks after that until it hits testing.

**Comment by richi235** [comment]
Great, thanks.
The experiments for my bachelor thesis will be in 3 weeks so 2 weeks
until the release is no problem. And even if not, self compiling is not that of an issue.
Cool and thanks for the fast reply.

**Comment by alexander-zimmermann** [comment]
@richi235 Instead of waiting for the new release, you can also checkout the next version from github and compile it from scratch. Should be easy. Alex
